### PR TITLE
maturin 0.11.2

### LINKED ISSUE #9: should toml be a run requirement?
toml is a requirement, but it's not installed when installing from conda-forge.

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Thanks for maintaining this!

- fixes #9

### CODE REVIEW

**Comment by bollwyvl** [comment]
Gah, don't have time time/resources to run down the OSX hard fail:

```
could not compile `unicode-linebreak`
```

Will add `--verbose` once windows finishes (or not :crying_cat_face: )

**Comment by bollwyvl** [comment]
From the logs:
```

2021-08-14T19:01:17.0251220Z   {"reason":"compiler-message","package_id":"unicode-linebreak 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-build","src_path":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-linebreak-0.1.1/build.rs","edition":"2018","doctest":false},"message":{"rendered":"error[E0277]: the trait bound `&[[u8; 44]; 53]: std::iter::IntoIterator` is not satisfied\n   --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-linebreak-0.1.1/build.rs:438:16\n    |\n438 |     for row in &pair_table {\n    |                ^^^^^^^^^^^ the trait `std::iter::IntoIterator` is not implemented for `&[[u8; 44]; 53]`\n    |\n    = help: the following implementations were found:\n              <&'a [T; N] as std::iter::IntoIterator>\n              <&'a [T] as std::iter::IntoIterator>\n              <&'a mut [T; N] as std::iter::IntoIterator>\n              <&'a mut [T] as std::iter::IntoIterator>\n    = note: required by `std::iter::IntoIterator::into_iter`\n\n","children":[{"children":[],"code":null,"level":"help","message":"the following implementations were found:\n  <&'a [T; N] as std::iter::IntoIterator>\n  <&'a [T] as std::iter::IntoIterator>\n  <&'a mut [T; N] as std::iter::IntoIterator>\n  <&'a mut [T] as std::iter::IntoIterator>","rendered":null,"spans":[]},{"children":[],"code":null,"level":"note","message":"required by `std::iter::IntoIterator::into_iter`","rendered":null,"spans":[]}],"code":{"code":"E0277","explanation":"You tried to use a type which doesn't implement some trait in a place which\nexpected that trait.\n\nErroneous code example:\n\n```compile_fail,E0277\n// here we declare the Foo trait with a bar method\ntrait Foo {\n    fn bar(&self);\n}\n\n// we now declare a function which takes an object implementing the Foo trait\nfn some_func<T: Foo>(foo: T) {\n    foo.bar();\n}\n\nfn main() {\n    // we now call the method with the i32 type, which doesn't implement\n    // the Foo trait\n    some_func(5i32); // error: the trait bound `i32 : Foo` is not satisfied\n}\n```\n\nIn order to fix this error, verify that the type you're using does implement\nthe trait. Example:\n\n```\ntrait Foo {\n    fn bar(&self);\n}\n\nfn some_func<T: Foo>(foo: T) {\n    foo.bar(); // we can now use this method since i32 implements the\n               // Foo trait\n}\n\n// we implement the trait on the i32 type\nimpl Foo for i32 {\n    fn bar(&self) {}\n}\n\nfn main() {\n    some_func(5i32); // ok!\n}\n```\n\nOr in a generic context, an erroneous code example would look like:\n\n```compile_fail,E0277\nfn some_func<T>(foo: T) {\n    println!(\"{:?}\", foo); // error: the trait `core::fmt::Debug` is not\n                           //        implemented for the type `T`\n}\n\nfn main() {\n    // We now call the method with the i32 type,\n    // which *does* implement the Debug trait.\n    some_func(5i32);\n}\n```\n\nNote that the error here is in the definition of the generic function: Although\nwe only call it with a parameter that does implement `Debug`, the compiler\nstill rejects the function: It must work with all possible input types. In\norder to make this example compile, we need to restrict the generic type we're\naccepting:\n\n```\nuse std::fmt;\n\n// Restrict the input type to types that implement Debug.\nfn some_func<T: fmt::Debug>(foo: T) {\n    println!(\"{:?}\", foo);\n}\n\nfn main() {\n    // Calling the method is still fine, as i32 implements Debug.\n    some_func(5i32);\n\n    // This would fail to compile now:\n    // struct WithoutDebug;\n    // some_func(WithoutDebug);\n}\n```\n\nRust only looks at the signature of the called function, as such it must\nalready specify all requirements that will be used for every type parameter.\n"},"level":"error","message":"the trait bound `&[[u8; 44]; 53]: std::iter::IntoIterator` is not satisfied","spans":[{"byte_end":17624,"byte_start":17613,"column_end":27,"column_start":16,"expansion":{"def_site_span":{"byte_end":0,"byte_start":0,"column_end":1,"column_start":1,"expansion":null,"file_name":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-linebreak-0.1.1/build.rs","is_primary":false,"label":null,"line_end":1,"line_start":1,"suggested_replacement":null,"suggestion_applicability":null,"text":[]},"macro_decl_name":"desugaring of `for` loop","span":{"byte_end":17624,"byte_start":17613,"column_end":27,"column_start":16,"expansion":null,"file_name":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-linebreak-0.1.1/build.rs","is_primary":false,"label":null,"line_end":438,"line_start":438,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":27,"highlight_start":16,"text":"    for row in &pair_table {"}]}},"file_name":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-linebreak-0.1.1/build.rs","is_primary":true,"label":"the trait `std::iter::IntoIterator` is not implemented for `&[[u8; 44]; 53]`","line_end":438,"line_start":438,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":27,"highlight_start":16,"text":"    for row in &pair_table {"}]}]}}
2021-08-14T19:01:17.0288560Z   {"reason":"compiler-message","package_id":"unicode-linebreak 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-build","src_path":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-linebreak-0.1.1/build.rs","edition":"2018","doctest":false},"message":{"rendered":"error: aborting due to previous error\n\n","children":[],"code":null,"level":"error","message":"aborting due to previous error","spans":[]}}
2021-08-14T19:01:17.0292220Z   {"reason":"compiler-message","package_id":"unicode-linebreak 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-build","src_path":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-linebreak-0.1.1/build.rs","edition":"2018","doctest":false},"message":{"rendered":"For more information about this error, try `rustc --explain E0277`.\n","children":[],"code":null,"level":"failure-note","message":"For more information about this error, try `rustc --explain E0277`.","spans":[]}}
2021-08-14T19:01:17.0296320Z   {"reason":"compiler-artifact","package_id":"env_logger 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"crate_types":["lib"],"name":"env_logger","src_path":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/env_logger-0.7.1/src/lib.rs","edition":"2018","doctest":true},"profile":{"opt_level":"3","debuginfo":null,"debug_assertions":false,"overflow_checks":false,"test":false},"features":["atty","default","humantime","regex","termcolor"],"filenames":["/private/tmp/pip-req-build-by1_j17m/target/release/deps/libenv_logger-276ff3bb6c6dc4cc.rlib","/private/tmp/pip-req-build-by1_j17m/target/release/deps/libenv_logger-276ff3bb6c6dc4cc.rmeta"],"executable":null,"fresh":false}
2021-08-14T19:01:17.0301020Z   {"reason":"compiler-artifact","package_id":"syn 1.0.73 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"crate_types":["lib"],"name":"syn","src_path":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.73/src/lib.rs","edition":"2018","doctest":true},"profile":{"opt_level":"3","debuginfo":null,"debug_assertions":false,"overflow_checks":false,"test":false},"features":["clone-impls","default","derive","extra-traits","full","parsing","printing","proc-macro","quote","visit"],"filenames":["/private/tmp/pip-req-build-by1_j17m/target/release/deps/libsyn-f4f6a6458556d933.rlib","/private/tmp/pip-req-build-by1_j17m/target/release/deps/libsyn-f4f6a6458556d933.rmeta"],"executable":null,"fresh":false}
```

**Comment by bollwyvl** [comment]
cc @conda-forge/help-rust (if there is such a thing)

**Comment by xhochy** [comment]
Can you try using `{{ compiler('rust') }}` instead of plain `rust` in build?

**Comment by bollwyvl** [comment]
Now seeing:

```
Undefined symbols for architecture x86_64:\n  \"_linkat\", referenced from:\n      std::sys::unix::fs::link::hcf1f5b95b4cdf3a4 in libstd-abe443acf5b6ec18.rlib(std-abe443acf5b6ec18.std.2kfg1vkb-cgu.0.rcgu.o)\nld: symbol(s) not found for architecture x86_64\nclang-11
```

Will try updating the SDK version...

**Comment by bollwyvl** [comment]
Looks like `rust 1.52` is insoluable on `osx-aarch64`, will try relaxing once more fails come through...

**Comment by xhochy** [comment]
We are using rust nightly om `osx-arm64`. If needed, try updating https://github.com/conda-forge/rust-feedstock/blob/dev/recipe/meta.yaml

**Comment by bollwyvl** [comment]
> We are using rust nightly om osx-arm64

Ah, yes, that might help. Issue from 79a977a  is `nonzero_leading_trailing_zeros`:

```
2021-08-15T17:47:51.2376740Z   {"reason":"compiler-message","package_id":"semver 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)","manifest_path":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-1.0.3/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"semver","src_path":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-1.0.3/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"message":{"rendered":"error[E0658]: use of unstable library feature 'nonzero_leading_trailing_zeros'\n   --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-1.0.3/src/identifier.rs:265:40\n    |\n265 |     let zero_bits_on_string_end = repr.leading_zeros();\n    |                                        ^^^^^^^^^^^^^\n    |\n    = note: see issue #79143 <https://github.com/rust-lang/rust/issues/79143> for more information\n    = help: add `#![feature(nonzero_leading_trailing_zeros)]` to the crate attributes to enable\n\n","children":[{"children":[],"code":null,"level":"note","message":"see issue #79143 <https://github.com/rust-lang/rust/issues/79143> for more information","rendered":null,"spans":[]},{"children":[],"code":null,"level":"help","message":"add `#![feature(nonzero_leading_trailing_zeros)]` to the crate attributes to enable","rendered":null,"spans":[]}],"code":{"code":"E0658","explanation":"An unstable feature was used.\n\nErroneous code example:\n\n```compile_fail,E0658\n#[repr(u128)] // error: use of unstable library feature 'repr128'\nenum Foo {\n    Bar(u64),\n}\n```\n\nIf you're using a stable or a beta version of rustc, you won't be able to use\nany unstable features. In order to do so, please switch to a nightly version of\nrustc (by using [rustup]).\n\nIf you're using a nightly version of rustc, just add the corresponding feature\nto be able to use it:\n\n```\n#![feature(repr128)]\n\n#[repr(u128)] // ok!\nenum Foo {\n    Bar(u64),\n}\n```\n\n[rustup]: https://rust-lang.github.io/rustup/concepts/channels.html\n"},"level":"error","message":"use of unstable library feature 'nonzero_leading_trailing_zeros'","spans":[{"byte_end":11391,"byte_start":11378,"column_end":53,"column_start":40,"expansion":null,"file_name":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-1.0.3/src/identifier.rs","is_primary":true,"label":null,"line_end":265,"line_start":265,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":53,"highlight_start":40,"text":"    let zero_bits_on_string_end = repr.leading_zeros();"}]}]}}
2021-08-15T17:47:51.2394590Z   {"reason":"compiler-message","package_id":"semver 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)","manifest_path":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-1.0.3/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"semver","src_path":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-1.0.3/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"message":{"rendered":"error[E0658]: use of unstable library feature 'nonzero_leading_trailing_zeros'\n   --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-1.0.3/src/identifier.rs:354:37\n    |\n354 |     let len_bits = usize_bits - len.leading_zeros() as usize;\n    |                                     ^^^^^^^^^^^^^\n    |\n    = note: see issue #79143 <https://github.com/rust-lang/rust/issues/79143> for more information\n    = help: add `#![feature(nonzero_leading_trailing_zeros)]` to the crate attributes to enable\n\n","children":[{"children":[],"code":null,"level":"note","message":"see issue #79143 <https://github.com/rust-lang/rust/issues/79143> for more information","rendered":null,"spans":[]},{"children":[],"code":null,"level":"help","message":"add `#![feature(nonzero_leading_trailing_zeros)]` to the crate attributes to enable","rendered":null,"spans":[]}],"code":{"code":"E0658","explanation":"An unstable feature was used.\n\nErroneous code example:\n\n```compile_fail,E0658\n#[repr(u128)] // error: use of unstable library feature 'repr128'\nenum Foo {\n    Bar(u64),\n}\n```\n\nIf you're using a stable or a beta version of rustc, you won't be able to use\nany unstable features. In order to do so, please switch to a nightly version of\nrustc (by using [rustup]).\n\nIf you're using a nightly version of rustc, just add the corresponding feature\nto be able to use it:\n\n```\n#![feature(repr128)]\n\n#[repr(u128)] // ok!\nenum Foo {\n    Bar(u64),\n}\n```\n\n[rustup]: https://rust-lang.github.io/rustup/concepts/channels.html\n"},"level":"error","message":"use of unstable library feature 'nonzero_leading_trailing_zeros'","spans":[{"byte_end":15313,"byte_start":15300,"column_end":50,"column_start":37,"expansion":null,"file_name":"/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-1.0.3/src/identifier.rs","is_primary":true,"label":null,"line_end":354,"line_start":354,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":50,"highlight_start":37,"text":"    let len_bits = usize_bits - len.leading_zeros() as usize;"}]}]}}
```

This feature stabilized in `1.54` (which i am giving a shot), and the current CF nightly is still on `1.53`, but there might be _yet more_ features (or the same ones), or it might not be solveable if there's already hard-coded stuff...

**Comment by bollwyvl** [comment]
https://github.com/conda-forge/rust-feedstock/pull/87 is ready for review, will give this another shot if/once that lands.

**Comment by bollwyvl** [comment]
@conda-forge-admin please restart ci

**Comment by bollwyvl** [comment]
@conda-forge/maturin ready for review.

**Comment by apcamargo** [comment]
Wow, a lot has happened. Thanks, @bollwyvl and @xhochy!

@messense do you still want to be added as a maintainer?

**Comment by messense** [comment]
> @messense do you still want to be added as a maintainer?

Yes, I'm happy to help maintaining this feedstock.

**Comment by apcamargo** [comment]
@conda-forge-admin please rerender

**Comment by messense** [comment]
@apcamargo I think you need to open a new issue to add new maintainers? https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list

**Comment by apcamargo** [comment]
@messense  As far as I known it only rerenders the repository, right? If there anything else involved I can open the issue after gerging this PR.

**Comment by messense** [comment]
The bot may also grant user write access to this repository I think?

**Comment by apcamargo** [comment]
Oh yeah, you're right. I'm rerendering and merging this PR and opening the issue afterwards.

**Comment by apcamargo** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
It looks like drone is continuing to take a walk... I'll add azure as the provider there: it's slower, but _finishes_.

Also, I'll re-add @messense: the initial rerender (a la 4bc8714, but with the azure change) will update the README, and once it's merged, you'll have maintainer rights.

**Comment by xhochy** [comment]
@bollwyvl Why aren't you using cross-compilation for the Linux builds? That is significantly faster.

**Comment by bollwyvl** [comment]
> Why aren't you using cross-compilation for the Linux builds?

'splain how, would love to know!

**Comment by xhochy** [comment]
> > Why aren't you using cross-compilation for the Linux builds?
> 
> 
> 
> 'splain how, would love to know!

Have a look at the `conda_forge.yml` There it is already enabled for  `osx-arm64`. You have to add entries like `build_platform: linux_aarch64: linux_64`

**Comment by bollwyvl** [comment]
> Have a look at the conda_forge.yml

Got it rerendered locally: will let this one run so we've got a datapoint (and maybe a roll-back point) for ef121f4, then push.

**Comment by bollwyvl** [comment]
Ha, went away for "a while" and see this is still chugging: i've opened #33 with @xochy's cross-compilation suggestion. It's a race!

**Pull request merged**
